project:
  type: website
  output-dir: docs
  
lang: es
  
website:
  title: "R en Buenos Aires"
  navbar:
    right: 
      - href: index.qmd
        text: Bienvenida
      - href: actividades.qmd
        text: "Actividades"
      - href: quienes-somos.qmd
        text: "Quienes Somos"
      - href: comunidades.qmd
        text: "Nuestra Red"
      - href: coc.qmd
        text: "Código de Conducta"
      - href: r-consortium.qmd
        text: "R consortium"
      - text: "Blog"
        href: blog.qmd
  page-footer:
    left: "© 2025 All rights reserved."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

