---
title: "Código de Conducta"
author: "Equipo Organizador"
format:
  html:
    css: titulo.css
editor: visual
---

> **Queremos que R en Buenos Aires sea un espacio libre de acoso.**

La comunidad de R en Buenos Aires, incluido su equipo organizador, debe conocer y seguir este Código de Conducta (basado en el de R Community). Su objetivo es fomentar el crecimiento de la comunidad en un entorno inclusivo, amigable y respetuoso.

Este Código se aplica a todos los espacios de participación de R en Buenos Aires —como reuniones, redes sociales, Slack y listas de correo— tanto presenciales como virtuales. También rige para quienes actúan en representación del grupo, incluso fuera de estos espacios.

## Comportamiento esperado

Esperamos que en todos los espacios de participación de R en Buenos Aires se mantenga una actitud respetuosa, colaborativa y considerada. Esto incluye conferencias, charlas, talleres, reuniones sociales, redes sociales y otros entornos digitales.


Algunas pautas de comportamiento son:


-   Reconocer y valorar los aportes de otras personas.

-   Ser amable y constructivo al expresar desacuerdos.

-   Mantener un discurso y acciones respetuosas en todo momento.

-   Colaborar activamente para prevenir conflictos.

-   Estar atento/a al entorno y a quienes lo rodean.

-   Informar al equipo organizador si se observa una situación riesgosa, alguien atravesando una experiencia incómoda o una posible violación de este Código, incluso si parece menor.

::: callout-important
El acoso incluye, entre otros: insultos directos o indirectos; daño verbal o escrito por motivos de género, orientación sexual, raza, religión o discapacidad; uso inapropiado de imágenes de desnudez (incluso en presentaciones); intimidación deliberada, acecho, persecución; fotografías o grabaciones abusivas; interrupciones sostenidas en presentaciones u otros eventos; contacto físico inapropiado y atención sexual no deseada.
:::

Quienes incumplan estas reglas podrán ser sancionados o expulsados del grupo. Si se te pide que detengas un comportamiento considerado inapropiado, esperamos que lo hagas de inmediato.


Valoramos los comentarios y las críticas constructivas: la diversidad de experiencias y habilidades enriquece nuestras actividades. Fomentamos un entorno en el que todas las personas puedan participar y generar un impacto positivo.


## ¿Querés comunicar una situación o pedir apoyo?

Si algo no está bien, podés comunicarte con el [equipo coordinador](https://renbaires.github.io/quienes-somos.html#equipo) o escribirnos a renbaires@gmail.com

Toda comunicación será tratada con absoluta discreción y cuidado.

## Aplicación del Código de Conducta

Este Código será aplicado por el equipo organizador, que será diverso y tendrá autoridad para resolver disputas. En los eventos presenciales habrá al menos una persona designada para su implementación, que podrá no ser parte del equipo organizador si fuera necesario. En caso de que una disputa involucre a alguien del equipo responsable, esa persona se apartará del proceso de toma de decisiones.